apiVersion: v1
data:
  cequel.yml: |
    development:
      host: 'cassandra.db.svc.cluster.local'
      port: 9042
      keyspace: blog_development
      max_retries: 3
      retry_delay: 0.5
      username: 'cassandra'
      password: 'CDqj9sEnIR'
      newrelic: false

    test:
      host: 'cassandra.db.svc.cluster.local'
      port: 9042
      keyspace: blog_test
      username: 'cassandra'
      password: 'CDqj9sEnIR'
      max_retries: 3
      retry_delay: 0.5
      newrelic: false

    production:
      hosts:
        - 'cassandra.db.svc.cluster.local'
      port: 9042
      keyspace: blog_production
      username: 'cassandra'
      password: 'CDqj9sEnIR'
      max_retries: 3
      retry_delay: 0.5
      newrelic: true
      replication:
        class: SimpleStrategy
        replication_factor: 1
    # replication:
    #   class: NetworkTopologyStrategy
    #   datacenter1: 3
    #   datacenter2: 2
    # durable_writes: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ include "railsapp.name" . }}